version: '3.8'

services:
  sitl:
    build:
      dockerfile: ./Dockerfile
    stdin_open: true # docker run -i
    tty: true
    network_mode: "host"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - "$HOME/ .Xauthority:/home/$USER/.Xauthority:ro"
      - /dev:/dev
    environment:
      - "DISPLAY=$DISPLAY"
